name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build  # Add build package
          pip install .[test]
      - name: Run tests with coverage
        run: |
          pytest --cov=scorefetch --cov-report=xml --cov-report=term
